### ISSUE TITLE
[Feature Request] Add a setting in scenario to set the repository URL to download from

### ISSUE THREAD

**Issue by Guts** [Guts/qgis-deployment-cli#271]
Useful for orgs that have a different repository endpoint depending on end-users.

```yaml
- name: Download plugins
  uses: qplugins-downloader
  with:
    force: false
    plugins_repository_url: https://qgis.myorg.net/plugins.xml
    threads: 5
```
Could be overridden by an environment variable: `QDT_PLUGINS_DOWNLOADER_REPOSITORY_URL`
