### ISSUE TITLE
[Feature Request]: add conditions on profile deployment

### ISSUE THREAD

**Issue by Guts** [Guts/qgis-deployment-cli#343]
### Context

Working with Grand Lyon to fit their IT needs which are:

- QDT is launched through a scheduled task (GPO are not allowed)
- every end-user belongs to various GIS groups

### Description

The goal is to add rules that condition the profile's installation into QGIS profiles folder. Could be something like this:

```yaml
  - name: Synchronize QGIS profiles between downloaded and installed
    uses: qprofiles-synchronizer
    with:
      sync_mode: only_new_version
      include:
        - profile_name: pvo
          rules:
            if: 'CG_SIG_PVO' in context.user.groups
        - profile_name: dryade
          rules:
            if: 'CG_SIG_ARB' in context.user.groups
        - profile_name: admin
          rules:
            if: 'QDT_USER_IS_QGIS_ADMIN' in context.user.environment
```

And in a `profile.json`:

```json
{
  "$schema": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "qdt_demo",
  "folder_name": "demo",
  "description": "Demo QGIS profile for QDT.",
  "author": "Oslandia",
  "email": "infos+qdt@oslandia.com",
  "version": "1.0.0",
  "rules": 
    {
     "value": "CG_SIG_PVO*",
     "conditions": "in",
     "target": "context.user.groups"
    }
}
```

### Related links

None

### Use Cases

Deploy only 

### Before submitting

- [X] I have verified that my idea is a change request and not a bug report.
