### ISSUE TITLE
[Feature Request]: Add a `search_paths` option to the qgis-installation-finder job

### ISSUE THREAD

**Issue by Guts** [Guts/qgis-deployment-cli#523]
### Description

Add a `search_paths` option to the qgis-installation-finder job like this:

```yml
- name: Find installed QGIS
  uses: qgis-installation-finder
  with:
    if_not_found: warning
    search_paths:
      - %PROGRAMFILES%\\QGIS x.y.z\\bin\
      - %QDT_OSGEO4W_INSTALL_DIR%
      - D:\\Applications\\QGIS\\
    version_priority:
      - "3.36"
```

A few remarks:

- the order matters
- the 

### Related links

- upstream issue: https://github.com/Guts/qgis-deployment-cli/issues/505
- job documentation: https://guts.github.io/qgis-deployment-cli/jobs/qgis_installation_finder.html

### Use Cases

Strategies for deploying QGIS on computer parks often opt for specific locations (typically outside `%PROGRAMFILES%`), notably for security reasons (a bit of unpredictability for outside people), backup or standardization of practices (typically the name of the QGIS installation folder is... not very clever.).

### Before submitting

- [X] I have verified that my idea is a change request and not a bug report.
